server:
    port: 8081

spring:
    application:
        name: channel-service
    datasource:
        url: jdbc:h2:mem:channeldb;DB_CLOSE_DELAY=-1
    jpa:
        hibernate:
            ddl-auto: update
